#!/usr/bin/env python3
"""Activity-log hook for Claude Code.

Appends a terse, timestamped breadcrumb to <project>/docs/activity-log.md every
time Claude edits or creates a file, and a commit marker whenever a git commit
runs. It logs file paths and line counts ONLY, never file contents, so secrets
never land in the log.

Wired as a global PostToolUse hook (see hooks/README.md). It is designed to
never fail or slow a tool call: any error is swallowed and it always exits 0.
"""
import sys
import os
import json
import subprocess
from datetime import datetime

LOG_REL = os.path.join("docs", "activity-log.md")

# Path fragments whose changes are noise (dependencies, build output, vcs).
IGNORE_FRAGMENTS = (
    os.sep + "node_modules" + os.sep,
    os.sep + ".git" + os.sep,
    os.sep + "dist" + os.sep,
    os.sep + "build" + os.sep,
    os.sep + ".next" + os.sep,
    os.sep + "target" + os.sep,        # Rust build dir
    os.sep + "__pycache__" + os.sep,
)

# Filenames we never log (the log itself, plus noisy lockfiles).
IGNORE_BASENAMES = (
    "activity-log.md",
    "bun.lock",
    "package-lock.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "Cargo.lock",
)

VERBS = {"Edit": "modified", "Write": "wrote", "NotebookEdit": "modified"}


def main():
    data = json.loads(sys.stdin.read())
    tool = data.get("tool_name", "")
    tool_input = data.get("tool_input") or {}
    root = os.environ.get("CLAUDE_PROJECT_DIR") or data.get("cwd") or os.getcwd()

    # Skip when the tool clearly failed, so we never record a change or a commit
    # that did not actually happen.
    if is_failure(data.get("tool_response")):
        return

    if tool == "Bash":
        log_commit(data, tool_input, root)
        return

    fpath = tool_input.get("file_path") or tool_input.get("notebook_path")
    if not fpath:
        return
    if os.path.basename(fpath) in IGNORE_BASENAMES:
        return
    if any(frag in fpath for frag in IGNORE_FRAGMENTS):
        return

    added, removed = count_changes(tool, tool_input)
    verb = VERBS.get(tool, "changed")
    rel = relpath(fpath, root)
    append(root, "%s  %-9s %s  (+%d/-%d)" % (now().strftime("%H:%M"), verb, rel, added, removed))


def is_failure(resp):
    """Best-effort detection of a failed tool call across the shapes a
    tool_response can take."""
    if isinstance(resp, dict):
        if resp.get("success") is False or resp.get("is_error") is True:
            return True
    return False


def log_commit(data, tool_input, root):
    cmd = tool_input.get("command", "")
    if "git commit" not in cmd:
        return
    # Avoid false positives: --dry-run does not create a commit, and
    # "git commit-graph" is a maintenance command, not a commit.
    if "--dry-run" in cmd or "commit-graph" in cmd:
        return
    # Read the resulting commit's subject directly from git, so this works no
    # matter how the message was supplied (-m, -F, heredoc, editor).
    try:
        subj = subprocess.run(
            ["git", "-C", root, "log", "-1", "--pretty=%s"],
            capture_output=True, text=True, timeout=5,
        ).stdout.strip()
    except Exception:
        subj = ""
    if subj:
        append(root, '  -- committed: "%s" --' % subj)


def count_changes(tool, tool_input):
    if tool == "Edit":
        return nlines(tool_input.get("new_string", "")), nlines(tool_input.get("old_string", ""))
    if tool == "Write":
        return nlines(tool_input.get("content", "")), 0
    return 0, 0


def nlines(s):
    if not s:
        return 0
    return s.count("\n") + (0 if s.endswith("\n") else 1)


def relpath(fpath, root):
    try:
        return os.path.relpath(fpath, root)
    except Exception:
        return fpath


def now():
    return datetime.now()


def append(root, line):
    log_path = os.path.join(root, LOG_REL)
    try:
        os.makedirs(os.path.dirname(log_path), exist_ok=True)
    except Exception:
        return
    git_exclude(root)

    header = "## " + now().strftime("%Y-%m-%d")
    needs_header = True
    if os.path.exists(log_path):
        last = None
        with open(log_path, "r", encoding="utf-8", errors="replace") as f:
            for ln in f:
                if ln.startswith("## "):
                    last = ln.strip()
        needs_header = last != header
    else:
        with open(log_path, "w", encoding="utf-8") as f:
            f.write("# Activity Log\n\nAuto-generated by the activity-log hook. Local only, never committed.\n")

    with open(log_path, "a", encoding="utf-8") as f:
        if needs_header:
            f.write("\n" + header + "\n\n")
        f.write(line + "\n")


def resolve_git_dir(root):
    """Return the repo's git directory, or None if root is not in a repo.

    Handles worktrees and submodules, where <root>/.git is a FILE containing a
    'gitdir: <path>' pointer instead of a directory. Without this, the exclude
    write would silently fail in those setups and the log would leak into
    git status."""
    p = os.path.join(root, ".git")
    if os.path.isdir(p):
        return p
    if os.path.isfile(p):
        try:
            with open(p, "r", encoding="utf-8", errors="replace") as f:
                content = f.read().strip()
        except Exception:
            return None
        if content.startswith("gitdir:"):
            gd = content[len("gitdir:"):].strip()
            if not os.path.isabs(gd):
                gd = os.path.normpath(os.path.join(root, gd))
            return gd
    return None


def git_exclude(root):
    """Keep the log invisible to git in ANY repo by adding it to
    info/exclude, which is local and never committed. This protects repos we do
    not own (the log never shows up in their git status)."""
    git_dir = resolve_git_dir(root)
    if not git_dir:
        return
    exclude = os.path.join(git_dir, "info", "exclude")
    entry = "docs/activity-log.md"
    try:
        existing = ""
        if os.path.exists(exclude):
            with open(exclude, "r", encoding="utf-8", errors="replace") as f:
                existing = f.read()
        if entry not in existing:
            os.makedirs(os.path.dirname(exclude), exist_ok=True)
            sep = "" if existing == "" or existing.endswith("\n") else "\n"
            with open(exclude, "a", encoding="utf-8") as f:
                f.write(sep + entry + "\n")
    except Exception:
        pass


if __name__ == "__main__":
    try:
        main()
    except Exception:
        pass
    sys.exit(0)
